package com.bbva.pisd.dto.insurance.utils;

public enum PISDProperties {

    ASO_MOCK_ENABLED("pisd.aso.mock.enabled"),
    ASO_MOCK_TIER_ENABLED("pisd.aso.mock.tier.enabled"),
    ASO_GET_TIER_MOCK("pisd.aso.get.tier.mock"),
    RIMAC_SIMULATION_MOCK("pisd.rimac.simulation.mock"),
    ID_API_CRYPTO("createCrypto"),
    ID_API_TIER("listCustomerClassifications"),
    ID_API_NOTIFICATIONS_GATEWAY_CREATE_EMAIL_SERVICE("createEmail"),
    ID_API_GIFOLE_CANCELLATION_SERVICE("gifole"),
    ID_API_SIMULATION_RIMAC("simulation.rimac"),
    URI_SIMULATION("/vehicular/V1/cotizacion"),
    ID_API_QUOTATION_DETAIL_RIMAC("quotationdetail.rimac"),
    URI_QUOTATION_DETAIL("/vehicular/V1/cotizacion/detalle/"),
    QUOTATION_DETAIL_QUERYSTRING("plan="),
    ID_API_QUOTATION_SELECTION_RIMAC("quotationselection.rimac"),
    URI_QUOTATION_SELECTION("/vehicular/V1/cotizacion/-/seleccionar"),
    X_API_KEY_RIMAC_HEADER("header.xapikey.simulation.rimac"),
    HOST_RIMAC_HEADER("header.host.simulation.rimac"),
    SIGNEDHEADERS_RIMAC("pisd.signedheaders.rimac"),

    RIMAC_AWS_REGION("pisd.region.rimac"),
    RIMAC_AWS_SERVICE_NAME("pisd.servicename.rimac"),
    RIMAC_ACCESS_KEY("pisd.accesskey.rimac"),
    RIMAC_SECRET_ACCESS_KEY("pisd.secretaccesskey.rimac"),

    KEY_OF_INSRC_LIST_RESPONSES("dtoInsurance"),
    FIELD_OR_FILTER_INSURANCE_RISK_BUSINESS_ID("INSURANCE_RISK_BUSINESS_ID"),
    FIELD_OR_FILTER_INSURANCE_MODALITY_TYPE("INSURANCE_MODALITY_TYPE"),
    FIELD_OR_FILTER_INSURANCE_PRODUCT_ID("INSURANCE_PRODUCT_ID"),

    QUERY_SELECT_INSRC_PRODUCT("PISD.SELECT_INSURANCE_PRODUCT"),
    FILTER_INSURANCE_PRODUCT_TYPE("INSURANCE_PRODUCT_TYPE"),
    FIELD_INSURANCE_PRODUCT_DESC("INSURANCE_PRODUCT_DESC"),

    QUERY_SELECT_INSRC_PRODUCT_FOR_RIMAC("PISD.SELECT_INSURANCE_BUSINESS"),
    FIELD_INSURANCE_BUSINESS_NAME("INSURANCE_BUSINESS_NAME"),

    QUERY_SELECT_INSRNC_PRD_MODALITY("PISD.SELECT_INSRNC_PRD_MODALITY"),
    FIELD_INSURANCE_COMPANY_MODALITY_ID("INSURANCE_COMPANY_MODALITY_ID"),
    FIELD_INSURANCE_MODALITY_NAME("INSURANCE_MODALITY_NAME"),
    FIELD_SUGGESTED_MODALITY_IND_TYPE("SUGGESTED_MODALITY_IND_TYPE"),

    QUERY_SELECT_CONSIDERATIONS("PISD.SELECT_CONSIDERATIONS"),
    FIELD_CNSD_PUBLICATION_ORDER_NUMBER("CNSD_PUBLICATION_ORDER_NUMBER"),
    FIELD_INSURANCE_CONSIDERATION_DESC("INSURANCE_CONSIDERATION_DESC"),
    FIELD_INSURANCE_CONSIDERATION_TYPE("INSURANCE_CONSIDERATION_TYPE"),
    FIELD_INSURANCE_CONSIDERATION_VALUE_TYPE("INSRC_CNSD_DATA_VALUE_TYPE"),
    FIELD_INSURANCE_CONSIDERATION_AMOUNT("INSURANCE_CONSIDERATION_AMOUNT"),
    FIELD_INSURANCE_CONSIDERATION_CURRENCY("CURRENCY_ID"),
    FIELD_INSURANCE_CONSIDERATION_PERCENTAGE("INSURANCE_CONSIDERATION_PER"),

    QUERY_SELECT_INSURANCE_SIMULATION_ID("PISD.SELECT_INSURANCE_SIMULATION_ID"),
    FIELD_Q_PISD_SIMULATION_ID0_NEXTVAL("NEXTVAL"),

    FIELD_LAST_CHANGE_BRANCH_ID("LAST_CHANGE_BRANCH_ID"),
    FIELD_SOURCE_BRANCH_ID("SOURCE_BRANCH_ID"),

    QUERY_INSERT_INSURANCE_SIMULATION("PISD.INSERT_INSURANCE_SIMULATION"),
    FIELD_INSRNC_COMPANY_SIMULATION_ID("INSRNC_COMPANY_SIMULATION_ID"),
    FIELD_CUSTOMER_ID("CUSTOMER_ID"),
    FIELD_CUSTOMER_SIMULATION_DATE("CUSTOMER_SIMULATION_DATE"),
    FIELD_CUST_SIMULATION_EXPIRED_DATE("CUST_SIMULATION_EXPIRED_DATE"),
    FIELD_BANK_FACTOR_TYPE("BANK_FACTOR_TYPE"),
    FIELD_BANK_FACTOR_AMOUNT("BANK_FACTOR_AMOUNT"),
    FIELD_BANK_FACTOR_PER("BANK_FACTOR_PER"),

    QUERY_INSERT_INSRNC_SIMLT_PRD("PISD.INSERT_INSRNC_SIMLT_PRD"),
    FIELD_INSURANCE_SIMULATION_ID("INSURANCE_SIMULATION_ID"),
    FIELD_CAMPAIGN_FACTOR_TYPE("CAMPAIGN_FACTOR_TYPE"),
    FIELD_CAMPAIGN_OFFER_1_AMOUNT("CAMPAIGN_OFFER_1_AMOUNT"),
    FIELD_CAMPAIGN_FACTOR_PER("CAMPAIGN_FACTOR_PER"),
    FIELD_SALE_CHANNEL_ID("SALE_CHANNEL_ID"),

    QUERY_INSERT_INSRNC_SIMLT_VEHICLE("PISD.INSERT_INSRNC_SIMLT_VEHICLE"),
    FIELD_VEHICLE_BRAND_ID("VEHICLE_BRAND_ID"),
    FIELD_VEHICLE_BRAND_NAME("VEHICLE_BRAND_NAME"),
    FIELD_VEHICLE_MODEL_ID("VEHICLE_MODEL_ID"),
    FIELD_VEHICLE_MODEL_NAME("VEHICLE_MODEL_NAME"),
    FIELD_VEHICLE_YEAR_ID("VEHICLE_YEAR_ID"),
    FIELD_COMMERCIAL_VEHICLE_AMOUNT("COMMERCIAL_VEHICLE_AMOUNT"),
    FIELD_CURRENCY_ID("CURRENCY_ID"),
    FIELD_NEW_VEHICLE_IND_TYPE("NEW_VEHICLE_IND_TYPE"),
    FIELD_VEHICLE_CIRCULATION_SCOPE_TYPE("VEHICLE_CIRCULATION_SCOPE_TYPE"),
    FIELD_VEH_CHANGE_RUDDER_IND_TYPE("VEH_CHANGE_RUDDER_IND_TYPE"),
    FIELD_VEHICLE_GAS_CONVERSION_TYPE("VEHICLE_GAS_CONVERSION_TYPE"),
    FIELD_VEHICLE_USE_TYPE("VEHICLE_USE_TYPE"),
    FIELD_VEHICLE_USAGE_DESC("VEHICLE_USAGE_DESC"),
    FIELD_VEHICLE_LICENSE_ID("VEHICLE_LICENSE_ID"),

    QUERY_SELECT_INSURANCE_SIMULATION_BY_QUOTATIONID("PISD.SELECT_INSURANCE_SIMULATION_BY_QUOTATIONID"),

    QUERY_INSERT_INSURANCE_QUOTATION("PISD.INSERT_INSURANCE_QUOTATION"),
    FIELD_POLICY_QUOTA_INTERNAL_ID("POLICY_QUOTA_INTERNAL_ID"),
    FIELD_INSURANCE_COMPANY_QUOTA_ID("INSURANCE_COMPANY_QUOTA_ID"),
    FIELD_QUOTE_DATE("QUOTE_DATE"),
    FIELD_POLICY_QUOTA_END_VALIDITY_DATE("POLICY_QUOTA_END_VALIDITY_DATE"),

    QUERY_INSERT_INSURANCE_QUOTATION_MOD("PISD.INSERT_INSURANCE_QUOTATION_MOD"),
    FIELD_PAYMENT_TERM_NUMBER("PAYMENT_TERM_NUMBER"),
    FIELD_POLICY_PAYMENT_FREQUENCY_TYPE("POLICY_PAYMENT_FREQUENCY_TYPE"),
    FIELD_FINANCING_START_DATE("FINANCING_START_DATE"),
    FIELD_FINANCING_END_DATE("FINANCING_END_DATE"),
    FIELD_PREMIUM_AMOUNT("PREMIUM_AMOUNT"),
    FIELD_PREMIUM_CURRENCY_ID("PREMIUM_CURRENCY_ID"),
    FIELD_SAVED_QUOTATION_IND_TYPE("SAVED_QUOTATION_IND_TYPE"),

    QUERY_INSERT_INSURANCE_QUOTATION_VEH("PISD.INSERT_INSURANCE_QUOTATION_VEH"),
    FIELD_REQUIRED_INSPECTION_IND_TYPE("REQUIRED_INSPECTION_IND_TYPE"),
    FIELD_GPS_IND_TYPE("GPS_IND_TYPE"),
    FIELD_CHASSIS_ID("CHASSIS_ID"),
    FIELD_VEHICLE_ENGINE_ID("VEHICLE_ENGINE_ID"),
    FIELD_VEHICLE_SEAT_NUMBER("VEHICLE_SEAT_NUMBER"),

    FIELD_CREATION_USER_ID("CREATION_USER_ID"),
    FIELD_USER_AUDIT_ID("USER_AUDIT_ID"),
    
    ASO_MOCK_BBVA_ENABLED("pisd.aso.mock.bbva.enabled"),
    ASO_MOCK_RIMAC_ENABLED("pisd.aso.mock.rimac.enabled"),
    ASO_GET_BLACKLISTBBVA_MOCK("pisd.aso.get.blacklistbbva.mock"),    
    ASO_GET_BLACKLISTHEALTHRIMAC_MOCK("pisd.aso.get.blacklisthealthrimac.mock"),    
    ASO_GET_BLACKLISTRISKRIMAC_MOCK("pisd.aso.get.blacklistriskrimac.mock"),    
    ID_API_BLACKLIST_ASO("blacklist.aso"),
    ID_API_BLACKLISTRISK_RIMAC("blacklistrisk.rimac"),
    ID_API_BLACKLISTHEALTH_RIMAC("blacklisthealth.rimac"),
    URI_BLACKLIST_RISK("/vehicular/V1/cotizacion/riesgoPersona/validar"),
	URI_BLACKLIST_HEALTH("/vehicular/V1/cotizacion/rechazoSalud/validar"),
	
	ASO_MOCK_SEARCH_ENABLED("pisd.aso.mock.search.enabled"),
    QUOTATION_SEARCH_QUERYSTRING_DOCUMENT_TYPE("tipoDocumento="),
    QUOTATION_SEARCH_QUERYSTRING_DOCUMENT_NUMBER("nroDocumento="),
    QUOTATION_SEARCH_QUERYSTRING_PLATE("placa="),
	ID_API_SEARCH_RIMAC("quotationsearch.rimac"),
	ASO_GET_SEARCH_MOCK("pisd.aso.get.search.mock"),
	QUERY_SELECT_INSRC_QUOTATION("PISD.SELECT_INSURANCE_QUOTATION"),
    KEY_REQUEST_INSRC_QUOTATION("POLICY_QUOTA_INTERNAL_ID"),
    URI_QUOTATION_SEARCH("/vehicular/V1/cotizacion/buscar"),

    QUERY_SELECT_INSURANCE_COMPANY_BY_COMPANYID("PISD.SELECT_INSURANCE_COMPANY"),
    FIELD_INSURANCE_COMPANY_DESC("INSURANCE_COMPANY_DESC"),

    QUERY_UPDATE_QUOTATION_REGISTER_ADDITIONAL_VEH("PISD.UPDATE_INSURANCE_QUOTATION_VEH"),
    URI_QUOTATION_REGISTER_ADDITIONAL("/vehicular/V1/cotizacion"),
    ID_API_QUOTATION_REGISTER_ADDITIONAL("quotationRegisterAdditional");

    private final String value;

    PISDProperties(String value) { this.value = value; }

    public String getValue() { return value; }

}